name: Mirror

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - mirror

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout this repository
    - name: Checkout Repository
      uses: actions/checkout@v4
        
    # Add the upstream remote
    - name: Add Upstream Remote
      run: |
        git remote add upstream https://gitlab.com/score-p/scorep.git
        git fetch upstream
        
    # Mirror the main/master branch
    - name: Push to Mirror
      run: |
        git checkout master
        git reset --hard upstream/master
        git push origin HEAD --force
